spring.application.name=sansaweigh
server.port=8095

spring.data.mongodb.uri=mongodb+srv://sebag20xx_db_user:GB2071bMYTXmXlQK@cluster0.6lrflxb.mongodb.net/sansaweigh?appName=Cluster0
spring.mongodb.uri=mongodb+srv://sebag20xx_db_user:GB2071bMYTXmXlQK@cluster0.6lrflxb.mongodb.net/sansaweigh?appName=Cluster0

spring.data.redis.host=localhost
spring.data.redis.port=6379

scale.api.url=http://localhost:9090/scales/

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
